# Use an official Node.js runtime as the base image
FROM node:latest AS build

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Install Angular CLI
RUN npm install -g @angular/cli

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the Angular app with production configuration
RUN ng build --configuration=production

# Use an official Nginx image as the base image
FROM nginx:alpine

# Copy the built Angular app to the appropriate location in the container
COPY --from=build /app/dist/fyle-internship-challenge-23-shiv /usr/share/nginx/html

# Expose port 80 for the Nginx server
EXPOSE 80

# Start the Nginx server when the container starts
CMD ["nginx", "-g", "daemon off;"]
